### ISSUE TITLE
Database Vulnerability

### ISSUE THREAD

**Issue by SulpherStaer** [eosfrontier/medicorum#5]
https://github.com/eosfrontier/medicorum/blob/ddbeee2c014d7ac1e11c5d9d62a4669081c0f5e5/getpatientlist.php#L20

Medicorum does not use the API as of yet, but this database query does not sanitize its input field. This is a database security risk. This must be fixed.

**Comment by willemm** [comment]
This line may look suspicious because of the 'concat' function, but that is actually the sql 'concat' function, which just sticks a few database fields together in the output.  This is not concat-ing input fields into a query string, this is not an input field (the query doesn't even have input fields) 

So there is no database security risk, and nothing to fix here.
